# docker-compose.yml

services:
  db:   # ← 이 이름이 MYSQL_HOST와 정확히 매칭돼야 함
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastapi_db
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: supersecret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backend:
    build: ./backend
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

volumes:
  db_data: